--- 
title: PRE-Maß Eta-Quadrat
---

# Aufgabe

 Sie wollen untersuchen, ob ältere Grundschulkinder mehr Taschengeld bekommen als jüngere. Sie haben dazu bei 10 Kindern die in der Tabelle abgetragenen Summen ermittelt. Zur Prüfung der Hypothese haben Sie zwei Kinder-Gruppen gebildet:

- Gruppe 1: Klasse 1 und 2 
- Gruppe 2: Klasse 3 und 4
 
 Berechnen Sie Eta-Quadrat und interpretieren Sie das Ergebnis!


| ID | Taschengeld pro Monat in Euro | Gruppe |
|----|-------------------------------|--------|
| 1  | 3                             | 1      |
| 2  | 9                             | 2      |
| 3  | 10                            | 1      |
| 4  | 4                             | 2      |
| 5  | 2                             | 1      |
| 6  | 4                             | 1      |
| 7  | 3                             | 2      |
| 8  | 6                             | 1      |
| 9  | 5                             | 2      |
| 10 | 6                             | 2      |

# Schritt 1
Variablen identifizieren: 

$$\text{Gruppe (unabhängig) (x)} \Rightarrow \text{Taschengeld pro Monat in Euro (abhängig) (y)}$$

Arithmetisches Mittel als bester Vorhersagewert, wenn keine
unabhängige Variable berücksichtigt wird (Quadratsumme gesamt)

$$
\bar{y}=\frac{3+9+10+4+2+4+3+6+5+6}{10}=5,2
$$


# Schritt 2

## Quadratsumme gesamt

$$
\sum(y_i - \bar{y})^2
$$
$$= (3-5,2)^2 + (9-5,2)^2 + (10-5,2)^2 + (4-5,2)^2 + (2-5,2)^2$$
$$+ (4-5,2)^2 + (3-5,2)^2 + (6-5,2)^2 + (5-5,2)^2 + (6-5,2)^2$$
$$=(-2,2)^2 + (3,8)^2 + (4,8)^2 + (-1,2)^2 + (-3,2)^2$$
$$+ (-1,2)^2 + (-2,2)^2 + (0,8)^2 + (-0,2)^2 + (0,8)^2$$
$$= 4,84 + 14,44 + 23,04 + 1,44 + 10,24 + 1,44 + 4,84 + 0,64 + 0,04 + 0,64$$
$$= 61.6$$

## Quadratsumme Gruppe 1

| ID | Taschengeld pro Monat in Euro | Gruppe |
|----|-------------------------------|--------|
| 1  | 3                             | 1      |
| 3  | 10                            | 1      |
| 5  | 2                             | 1      |
| 6  | 4                             | 1      |
| 8  | 6                             | 1      |

$$\bar{y} = \frac{3+10+2+4+6}{5}=5$$
$$\sum(y_i - \bar{y})^2 = (3-5)^2 + (10-5)^2 + (2-5)^2 + (4-5)^2 + (6-5)^2$$
$$= 2^2 + 5^5 + (-3)^2 + (-1)^2 + 1^2$$
$$= 4 + 25 + 9 + 1 + 1$$
$$= 40$$

## Quadratsumme Gruppe 2

| ID | Taschengeld pro Monat in Euro | Gruppe |
|----|-------------------------------|--------|
| 2  | 9                             | 2      |
| 4  | 4                             | 2      |
| 7  | 3                             | 2      |
| 9  | 5                             | 2      |
| 10 | 6                             | 2      |

$$\bar{y} = \frac{9+4+3+5+6}{5} = 5,4$$
$$\sum(y_i - \bar{y})^2 = (9-5,4)^2 + (4-5,4)^2 + (3-5,4)^2 + (5-5,4)^2 + (6-5,4)^2$$
$$= 3,6^2 + (-1,4)^2 + (-2,4)^2 + (-0,4)^2 + 0,6^2$$
$$= 12,96 + 1,96 + 5,76 + 0,16 + 0,36$$
$$= 21,2$$

## Quadratsumme innerhalb

$$\text{Quadratsumme}_\text{Innerhalb}=\text{Quadratsumme}_\text{Gruppe 1} + \text{Quadratsumme}_\text{Gruppe 2}$$ 
$$= 40 + 21,2 = 61.2$$

# Schritt 3

$\eta^2$-Formel anwenden


$$
\eta^2 = \frac{\text{Quadratsumme}_\text{Gesamt}-\text{Quadratsumme}_\text{Innerhalb}}{\text{Quadratsumme}_\text{Gesamt}} = \frac{\text{Quadratsumme}_\text{Zwischen}}{\text{Quadratsumme}_\text{Gesamt}}
$$

$$
\eta^2 = \frac{\text{E1}-\text{E2}}{\text{E1}} = \frac{61,6 - (40 + 21,2)}{61,6} = \frac{61,6 - 61,1}{61,6} = \frac{0,5}{61,6} = 0,0081
$$

Das $\eta^2$ ist sehr, sehr klein $\Rightarrow$
Es gibt keinen Effekt des Alters auf die höhe des Taschengeldes. 