---
title: Tutorium 6
date: 30.05.2023
toc: true
output: pdf_document
---

# Wiederholung von letztem Mal
Gegeben sei eine Verteilung von IQ-Werten mit $\mu = 100$ und $\sigma = 15$. Wie groß ist die Wahrscheinlichkeit, zufällig eine Person mit einem $IQ \leq 120$ auszuwählen, wenn diese Verteilung normalverteilt ist?
<details> <summary>Lösung</summary>
1. Z-Wert berechnen:
$z=\frac{x - \bar{x}}{s} = \frac{120IQ - 100IQ}{15IQ} = 1,333$

2. gesucht ist $P(IQ \leq 120) \rightarrow$ Wie groß ist die Fläche unter der Normalverteilung links von $z = 1,333$? $\rightarrow$ Z-Tabelle für 1,33: 0,9082 $\rightarrow$ 90,82%

</details>


# Aufgabe aus der VL 5 mit anderen Zahlen
$201$ Befragte mit einem Durchschnittsalter von $45$ Jahren und einer Standardabweichung von $9$ Jahren – in welchem Bereich liegt (mit $95\%$ Sicherheit) $\mu$?

a) Welche Werte werden benötigt um die kritischen t-Werte zu berechnen?
Konzeptionieren Sie das Vorgehen um die kritischen t-Werte zu berechnen.

b) Berechnen Sie den kritischen t-Werte und bestimmen Sie das Konfidenzintervall 

c) Interpretieren Sie das Ergebnis

<details> <summary>Lösung a) </summary>

1. $n,\bar{x},s$ bestimmen und gesuchte Fläche bestimmen
2. Geschätzte Standardabweichung berechnen
3. t-Wert ermitteln

</details>

<details> <summary>Lösung b) </summary>
[B.P.Kleer's Erklärvideo](https://vimeo.com/512472262)

1. 
$$
n = 201 \\
\bar{x} = 45 \\
s = 9
$$
2. Geschätzte Standardabweichung berechnen

Es ist nicht die korrigierte Standardabweichung angegeben, daher:
$\hat{\sigma}_x = \sqrt{s^2 \cdot \frac{n}{n-1}} = \sqrt{9^2 \cdot \frac{201}{200}} = 9.022472 \approx 9 \\ \hat{\sigma}_{\bar{x}} = \frac{\hat{\sigma}_x}{\sqrt{n}} = \frac{9}{\sqrt{201}} \approx 0,635$

3. t-Wert ermitteln
$$
x_u = \bar{x} - t_{(1-\frac{\alpha}{2};n-1)} \cdot \hat{\sigma}_{\bar{x}}\\
x_o = \bar{x} + t_{(1-\frac{\alpha}{2};n-1)} \cdot \hat{\sigma}_{\bar{x}}
$$
==> $1-\frac{\alpha}{2} = 1-\frac{0,05}{2} = 0,975$
Also ergibt sich:
$$
x_u = 45 - 1,972 \cdot 0,635 \approx 43,75\\
x_o = 45 + 1,972 \cdot 0,635 \approx 46,25
$$

</details>


<details> <summary>Lösung c) </summary>
Mit einer Sicherheit von 95% liegt der unbekannteErwartungswert des arithmetischen Mittels $\mu$ zwischen den Intervallsgrenzen 43,75 und 46,25

[Blog "Statistics by Jim" zu Konfidenzintervallen](https://statisticsbyjim.com/hypothesis-testing/confidence-interval/)

</details>


# Restliche Aufgaben aus der VL
Wie lautet der kritische t-Wert für df= 6 wenn $\alpha$= 0,05 (zweiseitig → 0,025 auf beiden Seiten)
<details> <summary>Lösung</summary>
$1-\frac{\alpha}{2} = 1-\frac{0,05}{2} = 0,975$

t-Wert nachschauen bei df=6; Fläche 0,975 ==> 2,447 
</details>


Wie lautet der kritische t-Wert bei einem n von 98
wenn $\alpha$= 0.05 (zweiseitig)?
<details> <summary>Lösung</summary>
$1-\frac{\alpha}{2} = 1-\frac{0,05}{2} = 0,975$

???
kurze recherche:
[Antwort 1](https://online.stat.psu.edu/stat500/book/export/html/521#:~:text=When%20the%20corresponding%20degree%20of,the%20precise%20t%2Dvalue)

[Antwort 2](https://socratic.org/questions/what-to-do-if-a-problem-has-a-non-tabled-degrees-of-freedom)

[Antwort 3](https://math.stackexchange.com/questions/4048287/standard-approach-for-critical-values-when-degree-of-freedom-is-missing-in-a-t-t)
</details>

# Aufgabe aus alten Tutorien
Welche Funktion erfüllt der Standardfehler?

<details> <summary>Lösung</summary>
Schätzt die  „Wahre“ Streuung $\sigma$ aus (empirischer)
Streuung $s$ in Stichprobe
$\hat{\sigma}_{\bar{x}}=\frac{s}{\sqrt{n}}$
</details>

# letzte Aufgabe aus VL
(fiktive) Links-Rechts- Selbsteinschätzung einer
Bevölkerung:
$\bar{x} = 5,822$; $s = 2,393$; $n = 1891$, gesucht: $95\%$ Konfidenzintervall: 
In welchem Intervall liegt mit $95\%$ Sicherheit $\mu$?

<details> <summary>Lösung</summary>

$\hat{\sigma}_{x}=\sqrt{s^2 \cdot \frac{n}{n-1}}=\sqrt{2,393^2 \cdot \frac{1891}{1890}}=2,393633$

$\hat{\sigma}_{\bar{x}} = \frac{\hat{\sigma}_{x}}{\sqrt{n}} = \frac{2,393633}{\sqrt{1891}} = 0,055$

$$
x_u = \bar{x} - t_{(1-\frac{\alpha}{2};n-1)} \cdot \hat{\sigma}_{\bar{x}}\\
x_o = \bar{x} + t_{(1-\frac{\alpha}{2};n-1)} \cdot \hat{\sigma}_{\bar{x}}
$$
$1-\frac{\alpha}{2} = 1-\frac{0,05}{2} = 0,975$

$$
x_u = 5,822 - 1,96 \cdot 0,055 = 5,7722\\
x_o = 5,822 + 1,96 \cdot 0,055 = 5,9878
$$
Mit einer Sicherheit von $95\%$ liegt der Mittelwert der Grundgesamtheit zwischen $5,772$ und $5,9878$

</details>


