---
title: "Normalverteilung - Übungsaufgaben"
author: "Serdar Selova, Alexander Lechner, Philipp Kleer - Team der Professur für
  Methoden der Politikwissenschaft - 08.04.2022"
date: "Lösungen hinzugefügt von Thomas Haase - 16.05.2023"
---

#### Was besagt das zentrale Grenzwerttheorem?

<details> <summary>Lösung</summary>
Eine Stichprobenkennwerteverteilung für unendlich viele Stichproben von Mittelwerten nähert sich der Normalverteilung an, falls die Stichproben ausreichend groß sind (n>= 30) oder die Werte in der GG normalverteilt sind

Stichprobenmittelwert geht gegen "wahren" Mittelwert
$$
\textrm{E}[\bar{x}] = \mu \\
\textrm{Var}[X]= \sigma^2
$$
</details>

#### Welche Bedingungen müssen erfüllt sein, damit eine Normalverteilung angenommen werden kann?
<details> <summary>Lösung</summary>
Die Daten müssen unabhängig identisch verteilt sein

[Link zu wikipedia](https://de.wikipedia.org/wiki/Unabh%C3%A4ngig_und_identisch_verteilte_Zufallsvariablen)
</details>


#### Wie groß ist der Flächenanteil der Standardnormalverteilung zwischen den Werten $z = -2$ und $z = 2$? 

<details> <summary>Lösung</summary>

$Fläche_{z = 2} - Fläche_{z = -2} = 0,9772 - 0,0228 = 0.9544$

</details>


#### Welchen Zweck erfüllt die z-Standardisierung?
<details> <summary>Lösung</summary>
Stellt Rohwerte relativ zur Verteilung dar, in der sich der Rohwert befindet
$$z=\frac{x_1 - \bar{x}}{s}$$
</details>


#### Beschreibe wie das Vorzeichen und der numerische Wert eines z-Wertes zu interpretieren ist.
<details> <summary>Lösung</summary>
$z = -1$: Rohwert liegt eine eine Standardabweichung unter dem Mittelwert der Verteilung

$z = 2$: Rohwert liegt 2 Standardabweichungen über dem Mittelwert der Verteilung
</details>

#### Welche Eigenschaft hat eine Standardnormalverteilung?
<details> <summary>Lösung</summary>
$$
\mu = 0 \\
\sigma = 1
$$
</details>

#### Erkläre in eigenen Worten wie du die z-Tabelle für einen Wert von z = −0.05 lesen musst.
<details> <summary>Lösung</summary>
[Formelsammlung](/home/thomas/Insync/thhaase.soz@gmail.com/GoogleDrive/_1_Projects/Sowi_4_Tutorium_Statistik 2/Tutorium 4/formelsammlung.pdf)
</details>

#### Bestimmte den Flächenanteil einer Normalverteilung, der den folgenden Bereichen entspricht.

(a) $z \leq 0.25$

(b) $z > 0.8$

(c) $z \leq −1.50$

(d) $z \leq 0.91$

(e) $z > 1.27$

(f) $z \leq 0.69$

<details> <summary>Lösung</summary>

in R mit pnorm() lösbar

(a) 0.5987063

(b) 1 - 0.7881446= 0.2118554$

(c) 0.0668072

(d) 0.8185887

(e) 1 - 0.8979577 = 0.1020423

(f) 0.7549029

</details>

    
#### Finde für eine Normalverteilung denjenigen z-Wert, der die Verteilung (annähernd) in die folgenden Bereiche unterteilt:

(a) obere 20%

(b) obere 60%

(c) mittlere70%

(d) obere 10%

(e) obere 70%

(f) mittlere 40%

<details> <summary>Lösung</summary>

in R mit qnorm() lösbar

(a) qnorm(1 - 0.8) = -0.8416212

(b) qnorm(1 - 0.4) = 0.2533471

(c) obere grenze: qnorm(0.85) = 1.036433 /// untere grenze: qnorm(0.15) = -1.036433

(d) qnorm(1 - 0.1) = 1.281552

(e) qnorm(1 - 0.7) = -0.5244

(f) $\frac{60}{2} = 30 \rightarrow$ qnorm(0.3) = -0.5244005 und 0.5244005

</details>
    
#### Gegeben sei eine Verteilung von IQ-Werten mit $\mu = 100$ und $\sigma = 15$. Wie groß ist die Wahrscheinlichkeit, zufällig eine Person mit einem $IQ \leq 120$ auszuwählen, wenn diese Verteilung
normalverteilt ist?
<details> <summary>Lösung</summary>
1. Z-Wert berechnen:
$z=\frac{x - \bar{x}}{s} = \frac{120IQ - 100IQ}{15IQ} = 1,333$

2. gesucht ist $P(IQ > 120) \rightarrow $ 

</details>
    




